
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.19.0
 * Query Engine version: 2ba551f319ab1df4bc874a89965d8b3641056773
 */
Prisma.prismaVersion = {
  client: "6.19.0",
  engine: "2ba551f319ab1df4bc874a89965d8b3641056773"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.UsersScalarFieldEnum = {
  id: 'id',
  username: 'username',
  email: 'email',
  extId: 'extId',
  discordId: 'discordId',
  discordUsername: 'discordUsername',
  kickId: 'kickId',
  kickUsername: 'kickUsername',
  role: 'role',
  customerId: 'customerId',
  timezone: 'timezone',
  plan: 'plan'
};

exports.Prisma.LimitsScalarFieldEnum = {
  id: 'id',
  date: 'date',
  aiUsed: 'aiUsed',
  aiLimit: 'aiLimit',
  additionalMessages: 'additionalMessages',
  premiumServers: 'premiumServers',
  premiumServerLimmit: 'premiumServerLimmit'
};

exports.Prisma.ServersScalarFieldEnum = {
  id: 'id',
  name: 'name',
  ownerId: 'ownerId',
  icon: 'icon',
  isPremium: 'isPremium',
  premiumAddedBy: 'premiumAddedBy',
  aiEnabled: 'aiEnabled',
  welcomeChannel: 'welcomeChannel',
  announcementChannel: 'announcementChannel',
  updatesChannel: 'updatesChannel',
  logsChannel: 'logsChannel',
  logLevel: 'logLevel',
  inviteLink: 'inviteLink',
  inviteCode: 'inviteCode',
  lastOpened: 'lastOpened',
  cleoPersonalityName: 'cleoPersonalityName',
  cleoPersonalityId: 'cleoPersonalityId'
};

exports.Prisma.PremiumSubscriptionsScalarFieldEnum = {
  id: 'id',
  tier: 'tier',
  startDate: 'startDate',
  endDate: 'endDate',
  source: 'source'
};

exports.Prisma.ServerSubscriptionsScalarFieldEnum = {
  id: 'id',
  startDate: 'startDate',
  endDate: 'endDate',
  source: 'source',
  subscriptionId: 'subscriptionId'
};

exports.Prisma.ErrorLogScalarFieldEnum = {
  id: 'id',
  process: 'process',
  message: 'message',
  stackTrace: 'stackTrace',
  timestamp: 'timestamp'
};

exports.Prisma.IncidentsScalarFieldEnum = {
  id: 'id',
  serverId: 'serverId',
  userId: 'userId',
  moderatorId: 'moderatorId',
  type: 'type',
  reason: 'reason',
  timestamp: 'timestamp',
  status: 'status'
};

exports.Prisma.ProductsScalarFieldEnum = {
  id: 'id',
  name: 'name',
  type: 'type'
};

exports.Prisma.PricesScalarFieldEnum = {
  id: 'id',
  amount: 'amount',
  default: 'default',
  productId: 'productId'
};

exports.Prisma.AutomodConfigScalarFieldEnum = {
  id: 'id',
  active: 'active',
  profanity: 'profanity',
  matureContent: 'matureContent',
  links: 'links',
  ignoredChannels: 'ignoredChannels',
  approvedLinks: 'approvedLinks',
  guildId: 'guildId'
};

exports.Prisma.TestimonialsScalarFieldEnum = {
  id: 'id',
  username: 'username',
  displayName: 'displayName',
  userImg: 'userImg',
  userId: 'userId',
  rating: 'rating',
  content: 'content',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.UserScalarFieldEnum = {
  id: 'id',
  name: 'name',
  email: 'email',
  emailVerified: 'emailVerified',
  image: 'image',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  lastLoginMethod: 'lastLoginMethod',
  username: 'username',
  locale: 'locale'
};

exports.Prisma.SessionScalarFieldEnum = {
  id: 'id',
  expiresAt: 'expiresAt',
  token: 'token',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  ipAddress: 'ipAddress',
  userAgent: 'userAgent',
  userId: 'userId'
};

exports.Prisma.AccountScalarFieldEnum = {
  id: 'id',
  accountId: 'accountId',
  providerId: 'providerId',
  userId: 'userId',
  accessToken: 'accessToken',
  refreshToken: 'refreshToken',
  idToken: 'idToken',
  accessTokenExpiresAt: 'accessTokenExpiresAt',
  refreshTokenExpiresAt: 'refreshTokenExpiresAt',
  scope: 'scope',
  password: 'password',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.VerificationScalarFieldEnum = {
  id: 'id',
  identifier: 'identifier',
  value: 'value',
  expiresAt: 'expiresAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};
exports.Role = exports.$Enums.Role = {
  staff: 'staff',
  user: 'user'
};

exports.Plans = exports.$Enums.Plans = {
  FREE: 'FREE',
  PREMIUM: 'PREMIUM',
  PREMIUMPLUS: 'PREMIUMPLUS',
  PRO: 'PRO'
};

exports.LogLevel = exports.$Enums.LogLevel = {
  NONE: 'NONE',
  MINIMAL: 'MINIMAL',
  MEDIUM: 'MEDIUM',
  MAXIMUM: 'MAXIMUM'
};

exports.Sources = exports.$Enums.Sources = {
  DISCORD: 'DISCORD',
  DASHBOARD: 'DASHBOARD'
};

exports.IncidentsType = exports.$Enums.IncidentsType = {
  WARN: 'WARN',
  KICK: 'KICK',
  BAN: 'BAN'
};

exports.IncidentsStatus = exports.$Enums.IncidentsStatus = {
  OPEN: 'OPEN',
  APPEALED: 'APPEALED',
  CLOSED: 'CLOSED',
  REVOKED: 'REVOKED'
};

exports.ProductType = exports.$Enums.ProductType = {
  onetime: 'onetime',
  subscription: 'subscription'
};

exports.Prisma.ModelName = {
  Users: 'Users',
  Limits: 'Limits',
  Servers: 'Servers',
  PremiumSubscriptions: 'PremiumSubscriptions',
  ServerSubscriptions: 'ServerSubscriptions',
  ErrorLog: 'ErrorLog',
  Incidents: 'Incidents',
  Products: 'Products',
  Prices: 'Prices',
  AutomodConfig: 'AutomodConfig',
  Testimonials: 'Testimonials',
  User: 'User',
  Session: 'Session',
  Account: 'Account',
  Verification: 'Verification'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
